export const UI_TEXT = {
  nav: { zukan: '図鑑', identify: '識別', plan: '計画', records: '記録', settings: '設定' },
  zukan: {
    title: 'キノコ図鑑', searchPlaceholder: '名前で検索...', filterToxicity: '毒性',
    filterSeason: '季節', filterHabitat: '生育地', noResults: '該当するキノコが見つかりません',
    season: 'シーズン', habitat: '生育地', regions: '分布地域', features: '形態的特徴',
    description: '概要', similarSpecies: '似ている種', caution: '注意事項',
    treeAssociation: '関連する樹種', seasonCalendarTitle: 'シーズンカレンダー',
    myRecords: '自分の採取記録', noRecords: 'この種の採取記録はありません',
  },
  identify: {
    title: '識別',
    detailTitle: '詳細識別',
    detailDescription: '写真をAIが分析し、候補種・根拠・注意すべき類似毒キノコを詳しく提示します。複数枚の写真で精度が向上します。',
    detailLabel: 'オンライン・Claude AI',
    simpleTitle: '簡易識別',
    simpleDescription: 'カメラで撮影し、デバイス内のAIが即時に候補を3種提示します。通信不要で現地でも使えます。',
    simpleLabel: 'オフライン・デバイス内',
    simpleComingSoon: 'Phase 4で追加予定',
    selectPrompt: 'キノコの写真から種類を推定します。用途に合った識別方法を選んでください。',
    requiresOnline: '要オンライン',
    requiresApiKey: '要APIキー',
    safetyWarning: 'どちらの識別もAIによる推定です。採取の最終判断は必ず専門家または経験者に確認してください。',
    resultSafetyWarning: 'AI推定です。採取の最終判断は専門家に確認してください。',
    photoHint: '異なる角度の写真で識別精度が向上します',
    addPhoto: '写真を追加',
    startIdentify: '識別を開始',
    identifying: '識別中...',
    resultTitle: '識別結果',
    confidenceHigh: '高',
    confidenceMedium: '中',
    confidenceLow: '低',
    similarToxicWarning: '類似する毒キノコ',
    viewInZukan: '図鑑で詳しく見る',
    retryIdentify: 'もう一度識別する',
    noPhotos: '写真を1枚以上選択してください',
    setupApiKey: 'APIキーを設定してください',
    goToSettings: '設定画面へ',
  },
  plan: {
    title: '採取計画',
    historyTitle: 'チャット履歴',
    historyButton: '履歴',
    formDescription: '採取計画の情報を入力してください。AIが安全で効率的な計画を提案します。',
    fieldDate: '予定日',
    fieldLocation: '場所',
    fieldLocationPlaceholder: '例: 高尾山周辺',
    fieldTarget: '探したいキノコ（任意）',
    fieldTargetPlaceholder: '図鑑から選択...',
    fieldExperience: '経験レベル',
    experienceBeginner: '初心者',
    experienceIntermediate: '中級者',
    experienceAdvanced: '上級者',
    startChat: '計画を相談する',
    inputPlaceholder: 'メッセージを入力...',
    sending: '送信中...',
    assistantLabel: 'アシスタント',
    userLabel: 'あなた',
    newSession: '新しい計画を作成',
    deleteSession: 'このチャットを削除しますか？',
    messageCount: 'メッセージ',
    noSessions: 'チャット履歴がありません',
    offlineSendDisabled: 'オフラインのため送信できません',
    setupApiKey: 'APIキーを設定すると採取計画機能が使えます',
  },
  records: {
    title: '採取記録',
    newRecord: '新規記録',
    editRecord: '記録を編集',
    deleteRecord: '記録を削除',
    deleteConfirm: 'この記録を削除しますか？',
    noRecords: '採取記録がありません',
    form: {
      mushroom: 'キノコの種類',
      mushroomPlaceholder: '図鑑から選択...',
      mushroomNameManual: '種名（手入力）',
      date: '日時',
      location: '場所',
      locationDescription: '場所の説明',
      locationPlaceholder: '例: 高尾山 6号路付近',
      gpsGet: '現在地を取得',
      gpsGetting: '取得中...',
      gpsFailed: '位置情報を取得できません。手動で入力してください。',
      photos: '写真',
      photosAdd: '写真を追加',
      quantity: '数量',
      quantityPlaceholder: '例: 3本',
      memo: 'メモ',
      harvested: '採取した',
      observed: '観察のみ',
      save: '保存',
      saving: '保存中...',
    },
    listView: 'リスト',
    mapView: '地図',
    filterBySpecies: '種別',
    filterByDate: '日付',
  },
  settings: {
    title: '設定',
    appInfo: 'アプリ情報',
    appName: 'MycoNote',
    appDescription: 'キノコ採取・観察ハンドブック',
    version: 'v0.2.0',
    aiSection: 'AI機能（Claude API）',
    apiKeyLabel: 'APIキー',
    apiKeyPlaceholder: 'sk-ant-...',
    apiKeySave: '保存',
    apiKeyDelete: '削除',
    apiKeyDeleteConfirm: 'APIキーを削除しますか？',
    apiKeyShow: '表示',
    apiKeyHide: '非表示',
    apiKeyConnected: '接続確認済み',
    apiKeyFailed: '接続に失敗しました',
    apiKeyTesting: '接続を確認中...',
    apiKeyDescription: 'APIキーはこの端末のlocalStorageに保存されます。サーバーには送信されません。',
    apiKeyGetLink: 'Anthropic ConsoleでAPIキーを取得 →',
  },
  common: {
    loading: '読み込み中...', error: 'エラーが発生しました',
    offline: 'オフラインモード — 一部機能が制限されています',
    onlineRestored: 'オンラインに復帰しました', back: '戻る',
    apiError401: 'APIキーが無効です。設定画面で確認してください。',
    apiError429: 'リクエストが多すぎます。しばらく待ってから再試行してください。',
    apiError500: 'サーバーエラーが発生しました。再試行してください。',
    apiErrorNetwork: 'オフラインのためAI機能を使用できません。',
    retry: '再試行',
  },
  months: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
} as const;
