export const UI_TEXT = {
  nav: { home: 'ホーム', zukan: '図鑑', identify: '識別', plan: '計画', records: '記録', settings: '設定' },
  home: {
    title: 'MycoNote',
    subtitle: 'キノコ採取・観察ハンドブック',
    seasonalTitle: '今月の旬',
    noSeasonal: '今月が旬のキノコはありません',
    quickAccess: 'クイックアクセス',
    safetyTip: 'Safety Tip',
    recentRecords: '最近の採取記録',
    noRecords: 'まだ採取記録がありません',
    quickZukan: '図鑑',
    quickIdentify: '識別',
    quickPlan: '採取計画',
    quickRecords: '採取記録',
    speciesCount: '種',
    viewAll: 'すべて見る',
  },
  zukan: {
    title: 'キノコ図鑑', searchPlaceholder: '名前で検索...', filterToxicity: '毒性',
    filterSeason: '季節', filterHabitat: '生育地', noResults: '該当するキノコが見つかりません',
    season: 'シーズン', habitat: '生育地', regions: '分布地域', features: '形態的特徴',
    description: '概要', similarSpecies: '似ている種', caution: '注意事項',
    cautionLabel: '注意事項',
    cooking: '調理・保存',
    firstAid: '中毒症状・応急処置',
    sources: '出典・ライセンス',
    taxonomy: '分類',
    taxonomyOrder: '目',
    taxonomyFamily: '科',
    taxonomyGenus: '属',
    treeAssociation: '関連する樹種', seasonCalendarTitle: 'シーズンカレンダー',
    myRecords: '自分の採取記録', noRecords: 'この種の採取記録はありません',
    googleImageSearch: 'Google で画像を検索',
    additionalPhotos: '野外写真（iNaturalist）',
    seasonCalendarFilter: '月で絞り込み',
    seasonCalendarAll: 'すべて',
    seasonCalendarCurrent: '今月',
    seasonCalendarEmpty: 'この月が旬のキノコはありません',
    // Tabs
    tabList: '一覧',
    tabBookmarks: '栞',
    tabSeason: '季節',
    // Sort
    sortBy: '並び順',
    sortSafety: '食用分類',
    sortKana: '五十音',
    sortTaxonomy: '分類学',
    // Filter accordion
    filterMore: 'もっと絞り込む',
    filterClose: '閉じる',
    filterClear: 'クリア',
    filterFamily: '科',
    filterGenus: '属',
    filterHabitatPlural: '生息地',
    filterRegions: '分布地域',
    filterTreeAssociation: '関連樹種',
    filterCapColor: '傘の色',
    // Bookmarks
    bookmarkAdd: '栞に追加',
    bookmarkRemove: '栞を外す',
    bookmarksEmpty: 'まだ栞はありません。気になる種を詳細ページから栞に追加できます。',
    bookmarkCount: '件',
    // Scroll to top
    scrollToTop: 'ページ上部へ戻る',
  },
  identify: {
    title: '識別',
    detailTitle: '詳細識別',
    detailDescription: '写真をAIが分析し、候補種・根拠・注意すべき類似毒キノコを詳しく提示します。複数枚の写真で精度が向上します。',
    detailLabel: 'オンライン・Claude AI',
    simpleTitle: '簡易識別',
    simpleDescription: '写真を見ながら特徴を選択し、候補種を表示します。通信不要で現地でも使えます。',
    simpleLabel: 'オフライン・特徴マッチング',
    selectPrompt: 'キノコの写真から種類を推定します。用途に合った識別方法を選んでください。',
    requiresOnline: '要オンライン',
    requiresApiKey: '要APIキー',
    safetyWarning: 'どちらの識別も参考情報です。採取の最終判断は必ず専門家または経験者に確認してください。',
    resultSafetyWarning: 'AI推定です。採取の最終判断は専門家に確認してください。',
    photoHint: '異なる角度の写真で識別精度が向上します',
    addPhoto: '写真を追加',
    takePhoto: '撮影',
    chooseFile: 'ファイル',
    startIdentify: '識別を開始',
    identifying: '識別中...',
    resultTitle: '識別結果',
    confidenceHigh: '高',
    confidenceMedium: '中',
    confidenceLow: '低',
    similarToxicWarning: '類似する毒キノコ',
    viewInZukan: '図鑑で詳しく見る',
    retryIdentify: 'もう一度識別する',
    noPhotos: '写真を1枚以上選択してください',
    setupApiKey: 'APIキーを設定してください',
    goToSettings: '設定画面へ',
    offlineAvailable: 'オフライン対応',
    simpleResultSafetyWarning: '簡易判定です。採取判断には使用しないでください。',
    referencePhoto: '参考写真',
    referencePhotoHint: '写真を見ながら特徴を選択してください',
    changePhoto: '写真を変更',
    gillType: 'ヒダのタイプ',
    gillTypeGills: 'ヒダ',
    gillTypePores: '管孔',
    gillTypeTeeth: '針状',
    gillTypeNone: 'なし',
    capColor: '傘の色',
    colorWhite: '白',
    colorBrown: '茶',
    colorRed: '赤',
    colorYellow: '黄',
    colorOrange: '橙',
    colorGray: '灰',
    colorBlack: '黒',
    capShape: '傘の形',
    shapeFlat: '平',
    shapeConvex: 'まんじゅう',
    shapeFunnel: '漏斗',
    shapeHemisphere: '半球',
    shapeConical: '円錐',
    capSize: '傘のサイズ',
    sizeSmall: '小 〜5cm',
    sizeMedium: '中 5〜15cm',
    sizeLarge: '大 15cm〜',
    moreFilters: 'もっと絞り込む',
    lessFilters: '絞り込みを閉じる',
    gillAttachment: 'ヒダの付き方',
    attachFree: '離生',
    attachAttached: '直生',
    attachDecurrent: '垂生',
    attachSinuate: '湾生',
    stalkColor: '柄の色',
    stalkFeatures: '柄の特徴',
    featureRing: 'つば有',
    featureVolva: 'つぼ有',
    featureHollow: '中空',
    featureFibrous: '繊維状',
    bruising: '変色反応',
    bruisingBlue: '青変',
    bruisingRed: '赤変',
    bruisingYellow: '黄変',
    bruisingNone: 'なし',
    substrateLabel: '発生場所',
    substrateBroadleaf: '広葉樹林',
    substrateConifer: '針葉樹林',
    substrateGrass: '草地',
    substrateDeadwood: '倒木上',
    seasonLabel: '発生時期',
    searchCandidates: '候補を検索',
    matched: '一致',
    changeConditions: '条件を変える',
    goToDetailIdentify: '詳細識別へ',
    // Phase 13-F: 簡易識別 一時停止
    simpleSuspendedTitle: '準備中',
    simpleSuspendedDescription: '簡易識別は v2 データ移行に伴い一時停止しています。順次再開予定です。AI 識別は引き続きご利用いただけます。',
    simpleSuspendedCTA: 'AI 識別を使う',
  },
  plan: {
    title: '採取計画',
    historyTitle: '採取計画の履歴',
    historyButton: '履歴',
    formDescription: '採取計画の情報を入力してください。AIが安全で効率的な計画を提案します。',
    fieldDate: '予定日',
    fieldLocation: '場所',
    fieldLocationPlaceholder: '例: 高尾山周辺',
    fieldTarget: '探したいキノコ（任意）',
    fieldTargetPlaceholder: '種名を入力（図鑑から候補表示）',
    fieldExperience: '経験レベル',
    experienceBeginner: '初心者',
    experienceIntermediate: '中級者',
    experienceAdvanced: '上級者',
    startChat: '計画を相談する',
    inputPlaceholder: 'メッセージを入力...',
    sending: '送信中...',
    assistantLabel: 'アシスタント',
    userLabel: 'あなた',
    newSession: '新しい計画を作成',
    deleteSession: 'この計画を削除しますか？',
    messageCount: 'メッセージ',
    noSessions: 'まだ計画の履歴はありません',
    offlineSendDisabled: 'オフラインのため送信できません',
    setupApiKey: 'APIキーを設定すると採取計画機能が使えます',
  },
  records: {
    title: '採取記録',
    newRecord: '新規記録',
    editRecord: '記録を編集',
    deleteRecord: '記録を削除',
    deleteConfirm: 'この記録を削除しますか？',
    noRecords: '採取記録がありません',
    form: {
      mushroom: 'キノコの種類',
      mushroomPlaceholder: '種名を入力（候補から選択、または自由入力）',
      mushroomRegistered: '図鑑に登録あり',
      mushroomNameManual: '種名（手入力）',
      date: '日時',
      location: '場所',
      locationDescription: '場所の説明',
      locationPlaceholder: '例: 高尾山 6号路付近',
      gpsGet: '現在地を取得',
      gpsGetting: '取得中...',
      gpsFailed: '位置情報を取得できません。手動で入力してください。',
      photos: '写真',
      photosAdd: '写真を追加',
      photosTake: '撮影',
      photosChoose: 'ファイル',
      autoFilledFromPhoto: '写真から補完',
      quantity: '数量',
      quantityPlaceholder: '例: 3本',
      memo: 'メモ',
      harvested: '採取した',
      observed: '観察のみ',
      save: '保存',
      saving: '保存中...',
    },
    listView: 'リスト',
    mapView: '地図',
    filterBySpecies: '種別',
    filterByDate: '日付',
  },
  settings: {
    title: '設定',
    // Phase 13-F / 14: お知らせ
    noticeSection: 'お知らせ',
    noticeV21Title: 'v2.1 — 収録種を 60 → 113 に拡充',
    noticeV21Body: '2026 年 4 月、tier1 として 53 種を追加しました（食用・有毒・稀少種を網羅的に）。画像は日本国内の観察を優先的に採用し、撮影者分散を最適化。ソース情報が薄い 5 種は tier2 候補として一旦保留しています。',
    noticeV2Title: 'v2.0 — データ刷新',
    noticeV2Body: '2026 年 4 月、出典付き・人間レビュー済みの 60 種で図鑑を作り直しました。v1 で報告のあったハルシネーション疑い種を排除するための再構築です。収録種は順次拡充されます。',
    noticeMigrationLabel: 'データ整合の結果',
    noticeMigrationBookmarks: '栞: {n} 件削除（参照先消失）',
    noticeMigrationRecords: '記録: {n} 件の種紐付けをリセット（記録自体は残ります）',
    noticeMigrationNoChange: '影響なし（v2 種のみ参照していた、または記録なし）',
    noticeMigrationRanAt: '実行日時:',
    appInfo: 'アプリ情報',
    appName: 'MycoNote',
    appDescription: 'キノコ採取・観察ハンドブック',
    // version は build 時に package.json + commit SHA から合成される。
    // 表示ロジック: @/constants/app-info の APP_VERSION_LABEL を参照。
    aiSection: 'AI機能（Claude API）',
    apiKeyLabel: 'APIキー',
    apiKeyPlaceholder: 'sk-ant-...',
    apiKeySave: '保存',
    apiKeyDelete: '削除',
    apiKeyDeleteConfirm: 'APIキーを削除しますか？',
    apiKeyShow: '表示',
    apiKeyHide: '非表示',
    apiKeyConnected: '接続確認済み',
    apiKeyFailed: '接続に失敗しました',
    apiKeyTesting: '接続を確認中...',
    apiKeyDescription: 'APIキーはこの端末のlocalStorageに保存されます。サーバーには送信されません。',
    apiKeyGetLink: 'Anthropic ConsoleでAPIキーを取得 →',
    dataSection: 'データ管理',
    exportButton: 'データをエクスポート',
    exportIncludePhotos: '写真を含める',
    exporting: 'エクスポート中...',
    exportingPhotos: '写真を変換中',
    exportComplete: 'エクスポートが完了しました',
    importButton: 'データをインポート',
    importing: 'インポート中...',
    importConfirm: 'をインポートしますか？',
    importComplete: 'インポートが完了しました',
    importRecords: 'レコード',
    importChats: 'チャット',
    importPhotos: '写真',
    importBookmarks: '栞',
    importAdded: '件追加',
    importSkipped: '件スキップ',
    importErrorFormat: 'ファイル形式が不正です',
    importErrorVersion: 'このバージョンのバックアップファイルには対応していません',
    importErrorInvalid: 'データ形式が不正です。正しいバックアップファイルを選択してください',
  },
  // Phase 13-F / 14: 起動時バナー (v2.1)
  banner: {
    v2Title: '収録種を拡充しました (v2.1)',
    v2Body: '2026 年 4 月、出典付き・人間レビュー済みの 113 種にアップデート (tier0 60 + tier1 53)。日本国内の観察写真を優先採用しています。詳細は設定 > お知らせをご覧ください。',
    dismiss: '閉じる',
  },
  common: {
    loading: '読み込み中...', error: 'エラーが発生しました',
    offline: 'オフラインモード — 一部機能が制限されています',
    onlineRestored: 'オンラインに復帰しました', back: '戻る',
    apiError401: 'APIキーが無効です。設定画面で確認してください。',
    apiError429: 'リクエストが多すぎます。しばらく待ってから再試行してください。',
    apiError500: 'サーバーエラーが発生しました。再試行してください。',
    apiErrorNetwork: 'オフラインのためAI機能を使用できません。',
    retry: '再試行',
  },
  months: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
} as const;
