export const UI_TEXT = {
  nav: { zukan: '図鑑', identify: '識別', plan: '計画', records: '記録', settings: '設定' },
  zukan: {
    title: 'キノコ図鑑', searchPlaceholder: '名前で検索...', filterToxicity: '毒性',
    filterSeason: '季節', filterHabitat: '生育地', noResults: '該当するキノコが見つかりません',
    season: 'シーズン', habitat: '生育地', regions: '分布地域', features: '形態的特徴',
    description: '概要', similarSpecies: '似ている種', caution: '注意事項',
    treeAssociation: '関連する樹種', seasonCalendarTitle: 'シーズンカレンダー',
    myRecords: '自分の採取記録', noRecords: 'この種の採取記録はありません',
  },
  identify: { title: '識別', comingSoon: 'この機能はPhase 3以降で実装予定です' },
  plan: { title: '採取計画', comingSoon: 'この機能はPhase 3以降で実装予定です' },
  records: {
    title: '採取記録',
    newRecord: '新規記録',
    editRecord: '記録を編集',
    deleteRecord: '記録を削除',
    deleteConfirm: 'この記録を削除しますか？',
    noRecords: '採取記録がありません',
    form: {
      mushroom: 'キノコの種類',
      mushroomPlaceholder: '図鑑から選択...',
      mushroomNameManual: '種名（手入力）',
      date: '日時',
      location: '場所',
      locationDescription: '場所の説明',
      locationPlaceholder: '例: 高尾山 6号路付近',
      gpsGet: '現在地を取得',
      gpsGetting: '取得中...',
      gpsFailed: '位置情報を取得できません。手動で入力してください。',
      photos: '写真',
      photosAdd: '写真を追加',
      quantity: '数量',
      quantityPlaceholder: '例: 3本',
      memo: 'メモ',
      harvested: '採取した',
      observed: '観察のみ',
      save: '保存',
      saving: '保存中...',
    },
    listView: 'リスト',
    mapView: '地図',
    filterBySpecies: '種別',
    filterByDate: '日付',
  },
  settings: {
    title: '設定', appInfo: 'アプリ情報', appName: 'MycoNote',
    appDescription: 'キノコ採取・観察ハンドブック', version: 'v0.1.0',
  },
  common: {
    loading: '読み込み中...', error: 'エラーが発生しました',
    offline: 'オフラインモード — 一部機能が制限されています',
    onlineRestored: 'オンラインに復帰しました', back: '戻る',
  },
  months: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
} as const;
